import torch

from train_acoustic_model_librispeech import AcousticModelConfig, TrainConfig, Trainer

run_configs = [
    # 460 hours
    {
        "n_semantic_types": 9116,
        "name": "ELLA-V-ZeroSylCollapsed-v040-k-9116-neucodec-LibriSpeech-train-clean-460",
        "segments_dir": "output/segments/ZeroSylCollapsed-v040-k-9116/LibriSpeech",
        "train_pattern": "train-clean*/**/*.pt",
        "valid_pattern": "dev*/**/*.pt",
        "steps": 20000,
        "warmup": 1600,
    },
    {
        "n_semantic_types": 8192,
        "name": "ELLA-V-SylBoost625-k-8192-neucodec-LibriSpeech-train-clean-460",
        "segments_dir": "output/segments/SylBoost625-k-8192/LibriSpeech",
        "train_pattern": "train-clean*/**/*.pt",
        "valid_pattern": "dev*/**/*.pt",
        "steps": 20000,
        "warmup": 1600,
    },
    {
        "n_semantic_types": 10001,
        "name": "ELLA-V-Sylber-k-10001-neucodec-LibriSpeech-train-clean-460",
        "segments_dir": "output/segments/Sylber-k-10001/LibriSpeech",
        "train_pattern": "train-clean*/**/*.pt",
        "valid_pattern": "dev*/**/*.pt",
        "steps": 20000,
        "warmup": 1600,
    },
    # 360 hours
    {
        "n_semantic_types": 9116,
        "name": "ELLA-V-ZeroSylCollapsed-v040-k-9116-neucodec-LibriSpeech-train-clean-460",
        "segments_dir": "output/segments/ZeroSylCollapsed-v040-k-9116/LibriSpeech",
        "train_pattern": "train-clean-360/**/*.pt",
        "valid_pattern": "dev*/**/*.pt",
        "steps": 15000,
        "warmup": 1200,
    },
    {
        "n_semantic_types": 8192,
        "name": "ELLA-V-SylBoost625-k-8192-neucodec-LibriSpeech-train-clean-460",
        "segments_dir": "output/segments/SylBoost625-k-8192/LibriSpeech",
        "train_pattern": "train-clean-360/**/*.pt",
        "valid_pattern": "dev*/**/*.pt",
        "steps": 15000,
        "warmup": 1200,
    },
    {
        "n_semantic_types": 10001,
        "name": "ELLA-V-Sylber-k-10001-neucodec-LibriSpeech-train-clean-460",
        "segments_dir": "output/segments/Sylber-k-10001/LibriSpeech",
        "train_pattern": "train-clean-360/**/*.pt",
        "valid_pattern": "dev*/**/*.pt",
        "steps": 15000,
        "warmup": 1200,
    },
    # 100 hours
    {
        "n_semantic_types": 9116,
        "name": "ELLA-V-ZeroSylCollapsed-v040-k-9116-neucodec-LibriSpeech-train-clean-460",
        "segments_dir": "output/segments/ZeroSylCollapsed-v040-k-9116/LibriSpeech",
        "train_pattern": "train-clean-100/**/*.pt",
        "valid_pattern": "dev*/**/*.pt",
        "steps": 5000,
        "warmup": 400,
    },
    {
        "n_semantic_types": 8192,
        "name": "ELLA-V-SylBoost625-k-8192-neucodec-LibriSpeech-train-clean-460",
        "segments_dir": "output/segments/SylBoost625-k-8192/LibriSpeech",
        "train_pattern": "train-clean-100/**/*.pt",
        "valid_pattern": "dev*/**/*.pt",
        "steps": 5000,
        "warmup": 400,
    },
    {
        "n_semantic_types": 10001,
        "name": "ELLA-V-Sylber-k-10001-neucodec-LibriSpeech-train-clean-460",
        "segments_dir": "output/segments/Sylber-k-10001/LibriSpeech",
        "train_pattern": "train-clean-100/**/*.pt",
        "valid_pattern": "dev*/**/*.pt",
        "steps": 5000,
        "warmup": 400,
    },
]

for run_config in run_configs:
    model_cfg = AcousticModelConfig(
        n_semantic_types=run_config["n_semantic_types"],
        n_acoustic_types=65536,
        semantic_freq=50.0,
        acoustic_freq=50.0,
        acoustic_lag=0.2,
        dim=768,
        n_layers=12,
        head_dim=64,
        hidden_dim=3072,
        n_heads=12,
        n_kv_heads=12,
        dropout=0.1,
        norm_eps=1e-6,
        rope_theta=10_000.0,
        force_fp32_attention=False,
    )
    train_cfg = TrainConfig(
        entity="zerospeech",
        project="zerosyl-acoustic-model",
        name=run_config["name"],
        device="cuda",
        dtype=torch.bfloat16,
        accumulation_steps=4,
        grad_clip_max_norm=1.0,
        batch_size=12,
        num_workers=23,
        train_segments_dir=run_config["segments_dir"],
        train_segments_pattern=run_config["train_pattern"],
        train_acoustic_units_dir="output/acoustic_units/distill-neucodec/LibriSpeech",
        train_acoustic_units_pattern=run_config["train_pattern"],
        valid_segments_dir=run_config["segments_dir"],
        valid_segments_pattern=run_config["valid_pattern"],
        valid_acoustic_units_dir="output/acoustic_units/distill-neucodec/LibriSpeech",
        valid_acoustic_units_pattern=run_config["valid_pattern"],
        lr_init=1e-7,
        lr_max=5e-4,
        lr_final=5e-5,
        n_linear_steps=run_config["warmup"],
        n_decay_steps=run_config["steps"] - run_config["warmup"],
        betas=(0.9, 0.98),
        weight_decay=0.01,
        eps=1e-8,
    )
    trainer = Trainer(model_cfg, train_cfg)
    trainer.train(
        max_global_step=run_config["steps"],
        log_every_n_global_steps=1,
        validate_every_n_global_steps=500,
    )
